name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'pnpm'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "anubra266@gmail.com"
        git config --global user.name "Abraham Anuoluwapo"

    - name: Install dependencies
      shell: bash
      run: pnpm install